### ISSUE TITLE
Conflicting README Information Regarding Use of StatefulSets

### ISSUE THREAD

**Issue by tonedefdev** [sonatype/helm3-charts#16]
It's listed in this [README](https://github.com/sonatype/helm3-charts/tree/master/nexus-repository-manager#persistence) that in order to use a persistent volume to enable statefulSet instead of using the default deployment. However, the values.yaml says it's not supported, and there's no templates relating to a statefulSet.

How are you supposed to guarantee a pod is reconnected to its PVC without a statefulSet in the event that it's recreated?

**Comment by CMYanko** [comment]
That's on me, I forked these from a set of Helm2 charts used in the operator. In NXRM I've worked on persistence but have been trying to avoid a stateful set because of its limitations on update strategies. Let me revisit the charts today and at least reconcile the docs and then I'll push on to persistence

**Comment by CMYanko** [comment]
Persistence is enable by default but I am not using a stateful set at this time. The Volumes use nexus.name and not fullname so it should get the same PV when upgrading
